// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMclcVeRJtNHSJFK2ohv1nuEoyFQDmKzg',
    appId: '1:1082687239278:web:b377e1c54c439a2a74a27f',
    messagingSenderId: '1082687239278',
    projectId: 'sansotietkiem',
    authDomain: 'sansotietkiem.firebaseapp.com',
    storageBucket: 'sansotietkiem.firebasestorage.app',
    measurementId: 'G-XBP3FH9E9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3ts8q2ciGmNT1BE4W33lAmQyE_pfXIU',
    appId: '1:1082687239278:android:8fdb1a025784f6c274a27f',
    messagingSenderId: '1082687239278',
    projectId: 'sansotietkiem',
    storageBucket: 'sansotietkiem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALhX5o62AzTIBxDqhuBBQv5YgmcmllBdc',
    appId: '1:1082687239278:ios:3082f27a2d75a8bb74a27f',
    messagingSenderId: '1082687239278',
    projectId: 'sansotietkiem',
    storageBucket: 'sansotietkiem.firebasestorage.app',
    iosBundleId: 'xyz.leanhtoan.flutterCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALhX5o62AzTIBxDqhuBBQv5YgmcmllBdc',
    appId: '1:1082687239278:ios:3082f27a2d75a8bb74a27f',
    messagingSenderId: '1082687239278',
    projectId: 'sansotietkiem',
    storageBucket: 'sansotietkiem.firebasestorage.app',
    iosBundleId: 'xyz.leanhtoan.flutterCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMclcVeRJtNHSJFK2ohv1nuEoyFQDmKzg',
    appId: '1:1082687239278:web:015ae7c886896eed74a27f',
    messagingSenderId: '1082687239278',
    projectId: 'sansotietkiem',
    authDomain: 'sansotietkiem.firebaseapp.com',
    storageBucket: 'sansotietkiem.firebasestorage.app',
    measurementId: 'G-WB8L5KTQH5',
  );
}
